### PR TITLE
Adding JEEA to endorsers

### PR DESCRIPTION
**Pull request by larsvilhuber**
Addresses #10

### CODE REVIEW

**Comment by korenmiklos** [comment]
@larsvilhuber is this waiting for endorsement from JEEA, or is this ready to merge?

**Comment by larsvilhuber** [comment]
JEEA (Andrea) has to approve, otherwise, it won't be merged.

--
Lars Vilhuber, Economist
Cornell University
p: +1.607-330-5743
https://calendly.com/larsvilhuber
My working day may not be your working day. Please respond during your working day.
________________________________

**Comment by larsvilhuber** [comment]
@korenmiklos when ready, this should be merged manually, into `main`, not `issue-12` (my bad)

**Comment by korenmiklos** [comment]
Resolved in #42

**Pull request closed without merging**
