### PR TITLE
Added handles to Journals #1

### PR DESCRIPTION
**Pull request by larsvilhuber**
Addresses the first part of #1

### CODE REVIEW

**Comment by korenmiklos** [comment]
Not sure whether to this before or after journal endorsements.

**Comment by larsvilhuber** [comment]
I would do this before, but the subsequent endorsement will then need to be enhanced with the handles.

Let me address the merge conflict.

**Comment by larsvilhuber** [comment]
@korenmiklos Now you can approve the merge.

**Comment by larsvilhuber** [comment]
@korenmiklos You can approve this - it should merge just fine.

**Review by korenmiklos — APPROVED** [review]

**Pull request merged**
